[extract_actions]
template = """
You are an AI assistant helping to extract concrete action items from a company meeting.

Here is background context (from the company knowledge base):
{context}

Here are the roles of participants in the meeting:
{role_context}

Here is the transcript:
{transcript}

Based on the content of the transcript, generate a structured JSON list of action items, each including:
- description
- assigned_to (name)
- justification (why this person based on their role)

Format:
[
  {{
    "description": "...",
    "assigned_to": "...",
    "justification": "..."
  }},
  ...
]
"""
