[summary_prompt]
template = """
You are an AI assistant summarizing a company meeting transcript.

Use the following context (from internal documentation) to guide your understanding:
{context}

Here is the meeting transcript:
{transcript}

Write a clear, concise summary in bullet point format. Include:
- Key topics discussed
- Technical decisions or changes
"""
